# note on node image: node:XX-slim images causes an error in watching file changes. Use node:XX-alpine or node:XX images instead
# see: https://github.com/nestjs/nest-cli/issues/484#issuecomment-616760770
FROM node:24
ENV NODE_ENV=development

WORKDIR /code
RUN apt update && apt install git -y
CMD npm install && npm i -g @angular/cli && npm run start
#CMD tail -f /etc/hosts


